FROM julia:1.11.2-alpine

# RUN sudo apt update && \
#     sudo apt install -y \
#     curl \
#     git \
#     unzip \
#     wget \
#     build-essential \
#     libtool \
#     pkg-config \
#     gettext \
#     cmake \
#     ninja-build \
#     python3-venv \
#     python3-pip \
#     ripgrep \
#     fzf \
#     neovim
#
WORKDIR /workspace

# Set the entrypoint to bash so you can run julia, nvim, etc.
ENTRYPOINT ["/bin/bash"]
